import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
    centeredView: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 22,
    },
    modalView: {
      margin: 20,
      backgroundColor: 'white',
      borderRadius: 20,
      padding: 35,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    imagebook: {
      borderRadius: 15,
      width: 200,
      height: 300,
      marginTop: 20,
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      alignContent: 'center',
    },
    bookTitle: {
      fontSize: 25,
      fontWeight: 'bold',
      alignSelf: 'center',
      justifyContent: 'center',
      textAlignVertical: 'center',
      alignContent: 'center',
      margin: 5,
    },
    bookAuthor: {
      fontSize: 18,
      margin: 10,
      alignSelf: 'center',
      justifyContent: 'center',
      textAlignVertical: 'center',
      alignContent: 'center',
      color: 'blue',
    },
    bookDesc: {
      fontSize: 15,
      marginLeft: 10,
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      textAlignVertical: 'center',
      alignContent: 'center',
    },
    styleBtn: {
      marginBottom: 0,
      marginTop: 0,
      marginLeft: 70,
      marginRight: 70,
      flex: 0,
      justifyContent: 'center',
      padding: 16,
    },
    container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#ecf0f1',
      padding: 8,
    },
  });